name: dv5_env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - gcc_linux-64
  - gxx_linux-64
  - gdb
  - m4
  - perl
  - swig
  - make 
  - zlib
  - libopenssl-static
  - openssl
  - cloudpickle
  - pip
  - pip:
    - fastjet==3.4.2.1
    - coffea==2024.4.0
    - dask==2024.7.1
    - dask-awkward==2024.7.0
    - awkward==2.6.6
post_install_script: install_taskvine.sh
